[package]
name = "soundscape"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
cpal = "0.17"
fundsp = "0.23"
rundsp = "0.1.1"
tunes = "1.1.0"
rand = "0.9"
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.29.0"
log = "0.4.29"
env_logger = "0.11.8"
